soal 1
#include <iostream>
#include <string>
using namespace std;

int main() {
    string s;
    cin >> s;

    int banyaknya_vokal = 0;
    for (char c : s) {
        if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u') {
            banyaknya_vokal++;
        }
    }

    cout << banyaknya_vokal << endl;
}

soal 2
dengan memasukkan codingan yang sama tetapi memasukkan coding an masukkan.txt ( loremipsumdolorsitametautpraesentiumevenietestaliasrationesitpossimusdoloresestdoloribusdolorintemporeipsaetdelenitirepudiandaeeosnequedistinctiosedbeataeaccusamussedexercitationemsolutaestmodivoluptateremnemovoluptasealaboriosamundeeumipsumnihiletdolorconsequatureaquiacorruptivelrepudiandaenemoeosquasfugiteatemporepossimusestipsumquiaestiustomolestiaequiistevoluptatibusnamquasidolorquilaboriosamvoluptateseaeaquevoluptatemexarchitectosapienteeaquiasapientequicupiditatesolutaeosminimafugaetnihilnostrumautdolorimpediteumdoloresnumquamsedtotamnostrumquivoluptatibussequiquiimpeditreprehenderitvelinternosdoloremestvoluptatemfugiatautvoluptatemrepellendusnonnostrumsintautsuscipitgalisumutomnisfugaidaliquamfugaquoullamfugaremvelitvitaequireprehenderitgalisumveldebitisoditnonasperioresinciduntnamdoloressuntetinventoreameteosquiaaliquamutautemquasestrepellatquisidaliquiddebitisinrecusandaeexplicabositipsumveroatminusomnisautinternosvoluptatumeospraesentiumenimeumteneturdoloremqueeumaperiamexcepturinonvoluptatemametuteaquedebitishicipsumesseinrecusandaequisestquasiautemautgalisumcupiditateetdoloremquemolestiasautprovidentsuntetquosillononipsumaccusamusautdignissimosgalisumautquianemoetomnisperferendisutmodiautemutvoluptatummodiestperferendisaliquamquodebitisducimusquiexcepturiiustoeumillovoluptatibusetmolestiaeconsequaturquinesciuntvoluptatesutculpamolestiaeeumdolorsintetofficiaconsequunturautexercitationemdoloremutrationeexcepturieospossimusevenietaconsequaturvelitsitomnissuscipitestquasperspiciatisadsimiliquenatusautharumexplicaboatporrodictaestvoluptatenihileumilloharumsedcorruptivoluptasexmaioresrerumquibeataequisquorepellendusodioquorerumreprehenderitquovoluptatemfugitquisaepelaboreutofficiaquamnonveniamquoseosmaximeperspiciatissedconsequaturmaioresquiblanditiistenetureainternosnihilaprovidentdoloreutdoloremquenemoetnequelaboreatvelitiurenonoptioofficiisetasperioressintetconsequaturaliquidquideserunttemporaeosomnisveniamestautemnemo33quamnobisutvoluptatemquideminnequenobisestdeseruntvoluptatemutvoluptatemnullautfugitvitaeetminimaimpeditremrerumaliasutvitaeisteautundedolorsedprovidentipsamsitullamrecusandaehicnequererumvelquiamolestiaeestvelitmagniutunderepellendusvelquiaharumquiaspernatursuntinquiarecusandaeeosrerumdolorumsitpraesentiumveroetmagniminimaestevenietlaboriosamutaliquamobcaecatietmollitiareprehenderitestsolutasintetquisconsecteturestomniseiusautducimusmolestiaseosautemnatushicminusrerumautvoluptatibusvoluptatemremnulladucimusautprovidentaccusantiumnonlaborumassumendaeumquisquamrerumautrerumaccusamusquirecusandaenatusquianimidoloretmollitiaveritatisutmollitiaminus

soal 3 
Ketika Anda menjalankan perintah berikut di terminal:
Windows:
hitung_vokal.exe < masukan.txt > keluaran.txt
Linux:
./hitung_vokal < masukan.txt > keluaran.txt
Tidak ada keluaran yang akan ditampilkan di layar.

Alasan:
Perintah tersebut menggunakan tanda > yang berfungsi untuk mengalihkan (redirect) keluaran program dari layar (standard output) ke file keluaran.txt.
Jadi, bukannya mencetak hasil ke layar, program akan menulis hasil (jumlah vokal) ke dalam file keluaran.txt.
